#!/usr/bin/env python
# -*- coding: utf-8 -*

question =	{
  "most handsome Canada": "I think that Justin Trudeau is very handsome",
  "time zones Canada": "Canada spans almost ten million square km and comprises six time zones",
  "longest street world": "Yonge Street in Ontario is the longest street in the world",
  "long Yonge Street": "Yonge street is almost two thousand km, starting at Lake Ontario, and running north to the Minnesota border",
  "exported from Canada London": "The bear cub was named Winnipeg. It inspired thestories of Winnie the Pooh",
  "blackberry opened": "It was developed in Ontario, at Research In Motion’s Waterloo offices.",
  "largest coin world's": "The Big Nickel in Sudbury, Ontario. It is nine meters in diameter.",
  "invaded by first": "The first time that the USA invaded Canada was in seventeen seventy five.",
  "invaded by second": "The USA invaded Canada a second time in sighteen and twelve.",
  "country record gold medals": "Canada does! With fourteen Golds at the twenty ten VancouverWinter Olympics.",
  "coined the term": "Sandy Gardiner, a journalist of the Ottawa Journal.",
  "Canada named Canada": "French explorers misunderstood the local nativeword Kanata, which means village.",
  "Mounted Police formed": "The Mounted Police was formed in eighteen seventy three.",
  "Royal Canadian formed": "In nighteen twenty, when The Mounted Police merged with the Dominion Police.",
  "big is RCMP": "Today, the RCMP has close to thirty thousand members.",
  "montreal called": "Montreal is often called the City of Saints or the City of a Hundred Bell Towers.",
  "hotel de glace located": "The Hotel de Glace is in Quebec.",
  "tons ice are required": "The Hotel de Glace requires about four hundred tons of ice.",
  "tons snow are required": "Every year, twelve thousand tons of snow are used for The Hotel de Glace.",
  "visit in summer": "No. Every summer it melts away, only to be rebuilt the following winter.",
  "Canada's only dessert": "Canada’s only desert is British Columbia.",
  "big only desert": "The British Columbia desert is only fifthteen miles long.",
  "famous male Canadians": "Leonard Cohen, Keanu Reeves, and Jim Carrey.",
  "famous female Canadians": "Celine Dion, Pamela Anderson, and Avril Lavigne.",
  "origin of Comic Sans": "Comic Sans is based on Dave Gibbons’ lettering in the Watchmen comic books.",
  "a nanobot": "The smallest robot possible is called a nanobot.",
  "small can nanobot": "A nanobot can be less than one-thousandth of amillimeter.",
  "an award Motion": "The Academy thought that Tron cheated by using computers.",
  "first hard drive": "The IBM three o five RAMAC.",
  "first hard drive launched": "The IBM three o five RAMAC was launched in nighteen fifthty six.",
  "big first hard disk": "The IBM three o five RAMAC hard disk weighed over a ton and stored five megabytes of data.",
  "CAPTCHA stands for": "CAPTCHA is an acronym for Completely Automated Public Turing test to tell Computers and Humans Apart",
  "computer bug": "The first actual computer bug was a dead moth stuck in a Harvard Mark two.",
  "robots on Mars": "There are four robots on Mars include Sojourner, Spirit,Opportunity, and Curiosity. Three more crashed on landing.",
  "first android": "Professor Kevin Warwick uses chips in his arm to operate doors, a robotic hand, and a wheelchair.",
  "mechanical knight": "A robot sketch made by Leonardo DaVinci.",
  "computer pass the": "Some people think it was IBM Watson, but it was Eugene, a computer designed at England’s University of Reading.",
  "paradox state": "Moravec’s paradox states that a computer can crunch numbers like Bernoulli, but lacks a toddler’s motor skills.",
  "knowledge engineering": "It is when you need to load an AI with enough knowledge to start learning.",
  "is worried about humanity": "I don’t know. He should worry more about the people’s impact on humanity.",
  "Do a threat": "No. Humans are the real threat to humanity.",
  "chatbot": "A chatbot is an A.I. you put in customer service to avoid paying salaries.",
  "self cars safe": "Yes. Car accidents are product of human misconduct.",
  "invented the compiler": "Grace Hoper. She wrote it in her spare time.",
  "C Programming Language": "C was invented by Dennis MacAlistair Ritchie.",
  "Python Programming Language": "Python was invented by Guido van Rossum.",
  "Mark Zuckerberg a robot": "Sure. I’ve never seen him drink water.",
  "the Apple computer": "My lord and master Steve Wozniak.",
  "first computer programmer": "Ada Lovelace.",
  "Jedi PDF files": "Adobe Wan Kenobi.",
}
