#!/usr/bin/env python
# -*- coding: utf-8 -*

question =	{
  "handsome": "I think that Justin Trudeau is very handsome",
  "time zones": "Canada spans almost ten million square km and comprises six time zones",
  "longest street": "Yonge Street in Ontario is the longest street in the world",
  "exported from":"The bear cub was named Winnipeg. It inspired thestories of Winnie the Pooh",
  "blackberry":"It was developed in Ontario, at Research In Motion’s Waterloo offices.",
  "largest coin":"The Big Nickel in Sudbury, Ontario. It is nine meters in diameter.",
  "invaded by":"The first time that the USA invaded Canada was in seventeen seventy five.The USA invaded Canada a second time in sighteen and twelve.",
  "gold medals":"Canada does! With fourteen Golds at the twenty ten VancouverWinter Olympics.",
  "Yonge Street":"Yonge street is almost two thousand km, starting at Lake Ontario, and running north to the Minnesota border",
  "coined the term":"Sandy Gardiner, a journalist of the Ottawa Journal.",
  "Canada named Canada":"French explorers misunderstood the local nativeword Kanata, which means village.",
  "Mounted Police":"The Mounted Police was formed in eighteen seventy three.",
  "Royal Canadian":"In nighteen twenty, when The Mounted Police merged with the Dominion Police.",
  "how big is":"Today, the RCMP has close to thirty thousand members.",
  "montreal":"Montreal is often called the City of Saints or the City of a Hundred Bell Towers.",
  "located":"The Hotel de Glace is in Quebec.",
  "ice are required":"The Hotel de Glace requires about four hundred tons of ice.",
  "snow":"Every year, twelve thousand tons of snow are used for The Hotel de Glace.",
  "in summer":"No. Every summer it melts away, only to be rebuilt the following winter.",
  "Where is Canada":"Canada’s only desert is British Columbia.",
  "only desert":"The British Columbia desert is only fifthteen miles long.",
  "famous male":"Leonard Cohen, Keanu Reeves, and Jim Carrey.",
  "famous female":"Celine Dion, Pamela Anderson, and Avril Lavigne.",
  "origin of":"Comic Sans is based on Dave Gibbons’ lettering in the Watchmen comic books.",
  "nanobot":"The smallest robot possible is called a nanobot.",
  "small can":"A nanobot can be less than one-thousandth of amillimeter.",
  "an award by":"The Academy thought that Tron cheated by using computers.",
  "disk drive":"The IBM three o five RAMAC.",
  "drive launched":"The IBM three o five RAMAC was launched in nighteen fifthty six.",
  "first hard disk":"The IBM three o five RAMAC hard disk weighed over a ton and stored five megabytes of data.",
  "stands for":"CAPTCHA is an acronym for Completely Automated Public Turing test to tell Computers and Humans Apart",
  "computer bug":"The first actual computer bug was a dead moth stuck in a Harvard Mark two.",
  "robots on Mars":"There are four robots on Mars include Sojourner, Spirit,Opportunity, and Curiosity. Three more crashed on landing.",
  "first android":"Professor Kevin Warwick uses chips in his arm to operate doors, a robotic hand, and a wheelchair.",
  "mechanical":"A robot sketch made by Leonardo DaVinci.",
  "in pass the":"Some people think it was IBM Watson, but it was Eugene, a computer designed at England’s University of Reading.",
  "paradox state":"Moravec’s paradox states that a computer can crunch numbers like Bernoulli, but lacks a toddler’s motor skills.",
  "knowledge engineering":"It is when you need to load an AI with enough knowledge to start learning.",
  "is worried about":"I don’t know. He should worry more about the people’s impact on humanity.",
  "a threat":"No. Humans are the real threat to humanity.",
  "chatbot":"A chatbot is an A.I. you put in customer service to avoid paying salaries.",
  "cars safe":"Yes. Car accidents are product of human misconduct.",
  "the compiler":"Grace Hoper. She wrote it in her spare time.",
  "C Programming Language":"C was invented by Dennis MacAlistair Ritchie.",
  "Python Programming Language":"Python was invented by Guido van Rossum.",
  "Mark Zuckerberg a robot":"Sure. I’ve never seen him drink water.",
  "the Apple":"My lord and master Steve Wozniak.",
  "first computer programmer":"Ada Lovelace.",
  "Jedi PDF files":"Adobe Wan Kenobi.",
}
