#!/usr/bin/env python
# -*- coding: utf-8 -*

question =	{
  "handsome person": "I think that Justin Trudeau is very handsome",
  "time zones": "Canada spans almost ten million square km and comprises six time zones",
  "longest street": "Yonge Street in Ontario is the longest street in the world",
  "Yonge Street": "Yonge street is almost two thousand km, starting at Lake Ontario, and running north to the Minnesota border",
  "1915": "The bear cub was named Winnipeg. It inspired thestories of Winnie the Pooh",
  "blackberry": "It was developed in Ontario, at Research In Motion's Waterloo offices.",
  "largest": "The Big Nickel in Sudbury, Ontario. It is nine meters in diameter.",
  "first time": "The first time that the USA invaded Canada was in seventeen seventy five.",
  "second time": "The USA invaded Canada a second time in sighteen and twelve.",
  "medals": "Canada does! With fourteen Golds at the twenty ten VancouverWinter Olympics.",
  "term": "Sandy Gardiner, a journalist of the Ottawa Journal.",
  "named": "French explorers misunderstood the local nativeword Kanata, which means village.",
  "Mounted Police": "The Mounted Police was formed in eighteen seventy three.",
  "Royal Canadian police": "In nighteen twenty, when The Mounted Police merged with the Dominion Police.",
  "RCMP": "Today, the RCMP has close to thirty thousand members.",
  "What else": "Montreal is often called the City of Saints or the City of a Hundred Bell Towers.",
  "located": "The Hotel de Glace is in Quebec.",
  "ice": "The Hotel de Glace requires about four hundred tons of ice.",
  "snow": "Every year, twelve thousand tons of snow are used for The Hotel de Glace.",
  "summer": "No. Every summer it melts away, only to be rebuilt the following winter.",
  "where only dessert": "Canada’s only desert is British Columbia.",
  "big only desert": "The British Columbia desert is only fifthteen miles long.",
  "male": "Leonard Cohen, Keanu Reeves, and Jim Carrey.",
  "female": "Celine Dion, Pamela Anderson, and Avril Lavigne.",
  "origin": "Comic Sans is based on Dave Gibbons' lettering in the Watchmen comic books",
  "nanobot": "The smallest robot possible is called a nanobot.",
  "small": "A nanobot can be less than one-thousandth of amillimeter.",
  "award": "The Academy thought that Tron cheated by using computers.",
  "which hard drive": "The IBM three o five RAMAC.",
  "when hard drive": "The IBM three o five RAMAC was launched in nighteen fifthty six.",
  "big hard disk": "The IBM three o five RAMAC hard disk weighed over a ton and stored five megabytes of data.",
  "CAPTCHA for": "CAPTCHA is an acronym for Completely Automated Public Turing test to tell Computers and Humans Apart",
  "bug": "The first actual computer bug was a dead moth stuck in a Harvard Mark two.",
  "Mars": "There are four robots on Mars include Sojourner, Spirit,Opportunity, and Curiosity. Three more crashed on landing.",
  "android": "Professor Kevin Warwick uses chips in his arm to operate doors, a robotic hand, and a wheelchair.",
  "mechanical": "A robot sketch made by Leonardo DaVinci.",
  "pass": "Some people think it was IBM Watson, but it was Eugene, a computer designed at England's University of Reading",
  "state": "Moravec's paradox states that a computer can crunch numbers like Bernoulli, but lacks a toddler’s motor skills.",
  "engineering": "It is when you need to load an AI with enough knowledge to start learning.",
  "worried impact humanity": "I don't know. He should worry more about the people’s impact on humanity.",
  "think": "No. Humans are the real threat to humanity.",
  "chatbot": "A chatbot is an A.I. you put in customer service to avoid paying salaries.",
  "safe": "Yes. Car accidents are product of human misconduct.",
  "invented compiler": "Grace Hoper. She wrote it in her spare time.",
  "C Programming Language": "C was invented by Dennis MacAlistair Ritchie.",
  "Python Programming Language": "Python was invented by Guido van Rossum.",
  "Mark": "Sure. I've never seen him drink water.",
  "Apple": "My lord and master Steve Wozniak.",
  "programmer": "Ada Lovelace.",
  "PDF": "Adobe Wan Kenobi.",
}
